### PR TITLE
New Icon & 7.1 Round Icon Support.

### PR DESCRIPTION
**Pull request by JediBurrell**

### CODE REVIEW

**Review by enricocid — CHANGES_REQUESTED** [review]
That's great, but please remove Windows thumbs.db files ;)

**Comment by enricocid** [comment]
Could You also provide 
512_512
1280_720
1024_500
180_120
dimensions and without any traspanrency?
I need them for the playstore graphics. Thanks.
You find my mail in my bio

**Comment by JediBurrell** [comment]
So sorry about that, yes, I can.

Though the 512x512 icon is supposed to have transparency, isn't it?

**Comment by enricocid** [comment]
the app icon YES

but if I update the app icon I also need to update the playstore graphics, and they don't want any transparency for them ;):)

For the playstore page I need 

the app icon in 512*512 without transparency

the banners (You can play around :P)
1280_720
1024_500
180*120

**Comment by JediBurrell** [comment]
Everything should be right, now. Not sure how you wanted the Play Store graphics, tell me if it needs altered.

**Comment by enricocid** [comment]
Thanks. Gonna update the apk and the playstore page as soon as possible :)

**Pull request merged**
